# Generated by Django 2.1.1 on 2018-10-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20181009_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.IntegerField()),
                ('game_name', models.CharField(max_length=50)),
                ('game_type', models.CharField(max_length=50)),
                ('game_description', models.CharField(max_length=200)),
                ('game_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('game_manufacturer', models.CharField(max_length=50)),
                ('game_year', models.IntegerField()),
            ],
        ),
    ]
